//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.AtividadeEntrevista.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARIOS
    {
        public long ID { get; set; }
        public string CPF { get; set; }
        public string NOME { get; set; }
        public long IDCLIENTE { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
