//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.AtividadeEntrevista.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.BENEFICIARIOS = new HashSet<BENEFICIARIOS>();
        }
    
        public long ID { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string NACIONALIDADE { get; set; }
        public string CEP { get; set; }
        public string ESTADO { get; set; }
        public string CIDADE { get; set; }
        public string LOGRADOURO { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public string CPF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENEFICIARIOS> BENEFICIARIOS { get; set; }
    }
}
