//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.AtividadeEntrevista.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancoDeDadosEntities : DbContext
    {
        public BancoDeDadosEntities()
            : base("name=BancoDeDadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENEFICIARIOS> BENEFICIARIOS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
    
        public virtual int FI_SP_AltBenef(string nOME, string cPF, Nullable<long> iD)
        {
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FI_SP_AltBenef", nOMEParameter, cPFParameter, iDParameter);
        }
    
        public virtual int FI_SP_AltCliente(string nOME, string sOBRENOME, string nACIONALIDADE, string cEP, string eSTADO, string cIDADE, string lOGRADOURO, string eMAIL, string tELEFONE, string cPF, Nullable<long> id)
        {
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sOBRENOMEParameter = sOBRENOME != null ?
                new ObjectParameter("SOBRENOME", sOBRENOME) :
                new ObjectParameter("SOBRENOME", typeof(string));
    
            var nACIONALIDADEParameter = nACIONALIDADE != null ?
                new ObjectParameter("NACIONALIDADE", nACIONALIDADE) :
                new ObjectParameter("NACIONALIDADE", typeof(string));
    
            var cEPParameter = cEP != null ?
                new ObjectParameter("CEP", cEP) :
                new ObjectParameter("CEP", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var cIDADEParameter = cIDADE != null ?
                new ObjectParameter("CIDADE", cIDADE) :
                new ObjectParameter("CIDADE", typeof(string));
    
            var lOGRADOUROParameter = lOGRADOURO != null ?
                new ObjectParameter("LOGRADOURO", lOGRADOURO) :
                new ObjectParameter("LOGRADOURO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tELEFONEParameter = tELEFONE != null ?
                new ObjectParameter("TELEFONE", tELEFONE) :
                new ObjectParameter("TELEFONE", typeof(string));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FI_SP_AltCliente", nOMEParameter, sOBRENOMEParameter, nACIONALIDADEParameter, cEPParameter, eSTADOParameter, cIDADEParameter, lOGRADOUROParameter, eMAILParameter, tELEFONEParameter, cPFParameter, idParameter);
        }
    
        public virtual ObjectResult<FI_SP_ConsCliente_Result> FI_SP_ConsCliente(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FI_SP_ConsCliente_Result>("FI_SP_ConsCliente", iDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> FI_SP_IncClienteV(string nOME, string sOBRENOME, string nACIONALIDADE, string cEP, string eSTADO, string cIDADE, string lOGRADOURO, string eMAIL, string tELEFONE, string cPF)
        {
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sOBRENOMEParameter = sOBRENOME != null ?
                new ObjectParameter("SOBRENOME", sOBRENOME) :
                new ObjectParameter("SOBRENOME", typeof(string));
    
            var nACIONALIDADEParameter = nACIONALIDADE != null ?
                new ObjectParameter("NACIONALIDADE", nACIONALIDADE) :
                new ObjectParameter("NACIONALIDADE", typeof(string));
    
            var cEPParameter = cEP != null ?
                new ObjectParameter("CEP", cEP) :
                new ObjectParameter("CEP", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var cIDADEParameter = cIDADE != null ?
                new ObjectParameter("CIDADE", cIDADE) :
                new ObjectParameter("CIDADE", typeof(string));
    
            var lOGRADOUROParameter = lOGRADOURO != null ?
                new ObjectParameter("LOGRADOURO", lOGRADOURO) :
                new ObjectParameter("LOGRADOURO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tELEFONEParameter = tELEFONE != null ?
                new ObjectParameter("TELEFONE", tELEFONE) :
                new ObjectParameter("TELEFONE", typeof(string));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("FI_SP_IncClienteV", nOMEParameter, sOBRENOMEParameter, nACIONALIDADEParameter, cEPParameter, eSTADOParameter, cIDADEParameter, lOGRADOUROParameter, eMAILParameter, tELEFONEParameter, cPFParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> FI_SP_IncClienteV2(string nOME, string sOBRENOME, string nACIONALIDADE, string cEP, string eSTADO, string cIDADE, string lOGRADOURO, string eMAIL, string tELEFONE, string cPF)
        {
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sOBRENOMEParameter = sOBRENOME != null ?
                new ObjectParameter("SOBRENOME", sOBRENOME) :
                new ObjectParameter("SOBRENOME", typeof(string));
    
            var nACIONALIDADEParameter = nACIONALIDADE != null ?
                new ObjectParameter("NACIONALIDADE", nACIONALIDADE) :
                new ObjectParameter("NACIONALIDADE", typeof(string));
    
            var cEPParameter = cEP != null ?
                new ObjectParameter("CEP", cEP) :
                new ObjectParameter("CEP", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var cIDADEParameter = cIDADE != null ?
                new ObjectParameter("CIDADE", cIDADE) :
                new ObjectParameter("CIDADE", typeof(string));
    
            var lOGRADOUROParameter = lOGRADOURO != null ?
                new ObjectParameter("LOGRADOURO", lOGRADOURO) :
                new ObjectParameter("LOGRADOURO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tELEFONEParameter = tELEFONE != null ?
                new ObjectParameter("TELEFONE", tELEFONE) :
                new ObjectParameter("TELEFONE", typeof(string));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("FI_SP_IncClienteV2", nOMEParameter, sOBRENOMEParameter, nACIONALIDADEParameter, cEPParameter, eSTADOParameter, cIDADEParameter, lOGRADOUROParameter, eMAILParameter, tELEFONEParameter, cPFParameter);
        }
    
        public virtual int FI_SP_PesqCliente(Nullable<int> iniciarEm, Nullable<int> quantidade, string campoOrdenacao, Nullable<bool> crescente)
        {
            var iniciarEmParameter = iniciarEm.HasValue ?
                new ObjectParameter("iniciarEm", iniciarEm) :
                new ObjectParameter("iniciarEm", typeof(int));
    
            var quantidadeParameter = quantidade.HasValue ?
                new ObjectParameter("quantidade", quantidade) :
                new ObjectParameter("quantidade", typeof(int));
    
            var campoOrdenacaoParameter = campoOrdenacao != null ?
                new ObjectParameter("campoOrdenacao", campoOrdenacao) :
                new ObjectParameter("campoOrdenacao", typeof(string));
    
            var crescenteParameter = crescente.HasValue ?
                new ObjectParameter("crescente", crescente) :
                new ObjectParameter("crescente", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FI_SP_PesqCliente", iniciarEmParameter, quantidadeParameter, campoOrdenacaoParameter, crescenteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> FI_SP_VerificaCliente(string cPF)
        {
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("FI_SP_VerificaCliente", cPFParameter);
        }
    
        public virtual int FI_SP_IncCliente(string cPF, string nOME, string sOBRENOME, string nACIONALIDADE, string cEP, string eSTADO, string cIDADE, string lOGRADOURO, string eMAIL)
        {
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sOBRENOMEParameter = sOBRENOME != null ?
                new ObjectParameter("SOBRENOME", sOBRENOME) :
                new ObjectParameter("SOBRENOME", typeof(string));
    
            var nACIONALIDADEParameter = nACIONALIDADE != null ?
                new ObjectParameter("NACIONALIDADE", nACIONALIDADE) :
                new ObjectParameter("NACIONALIDADE", typeof(string));
    
            var cEPParameter = cEP != null ?
                new ObjectParameter("CEP", cEP) :
                new ObjectParameter("CEP", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var cIDADEParameter = cIDADE != null ?
                new ObjectParameter("CIDADE", cIDADE) :
                new ObjectParameter("CIDADE", typeof(string));
    
            var lOGRADOUROParameter = lOGRADOURO != null ?
                new ObjectParameter("LOGRADOURO", lOGRADOURO) :
                new ObjectParameter("LOGRADOURO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FI_SP_IncCliente", cPFParameter, nOMEParameter, sOBRENOMEParameter, nACIONALIDADEParameter, cEPParameter, eSTADOParameter, cIDADEParameter, lOGRADOUROParameter, eMAILParameter);
        }
    }
}
